### ISSUE TITLE
是如何判断app crash的呢，麻烦告知

### ISSUE THREAD

**Issue by zhaoyh1991** [284772894/appiumn_auto#11]
def pull_crash_log(self):
        log = ""
        print("pull_crash_log")
        _read_crash = basePickle.read_pickle(common.CRASH_LOG_PATH)
        if len(_read_crash) > 0:
            for i in range(len(_read_crash)):
                if _read_crash[i]["devices"] == self.get_phone_name()[1]:  # 如果android 传过来的device和现在测试的decvice相匹配
                    log = _read_crash[i]["log"]
                    rand_log = baseRandom.get_ran_dom() + ".log"  # 随机的log文件
                    push_log = common.APACHE_PATH + rand_log  # 存到apache的路径里面
                    os.system("adb -s " + self.devices + " pull " + log + " " + push_log)
                    return common.PROTOCOL + common.HOST + "/" + common.APACHE_PATH + rand_log
        return log
这里的log = _read_crash[i]["log"]是怎么设置的，设置的什么路径呢？这里返回log地址就表示崩溃是什么原理呢，没理解，希望能有人帮助解答

**Comment by Louis-me** [comment]
原理是app那里我自定义封装了一个监控闪退的sdk，发现闪退后，主动把错误日志发给自动化测试这里myserver
- [异常类监控](https://github.com/Louis-me/CrashHandler)
- [自动化测试框架的my server](https://github.com/Louis-me/appiumn_auto/blob/master/Common/myserver.py)

**Comment by zhaoyh1991** [comment]
感谢在百忙中解答我的问题！！我现在理解是在监控程序检测到crash后会请求一次http服务告知crash log路径所以在appium会发现这次操作crash了拉取日志到apach服务器。感谢，祝假期愉快！！
