### ISSUE TITLE
运行后经常连接不上设备

### ISSUE THREAD

**Issue by javarike** [284772894/appiumn_auto#2]
运行后经常连接不上设备，运行五次有三次找不到我的设备，win7 64bit，安卓4.4.2，设备检查方面待完善也。。。我安装了360助手，不知道影响大不？

**Comment by javarike** [comment]
`info: Retrieving device

info: [debug] Trying to find a connected android device

info: [debug] Getting connected devices...

info: [debug] executing cmd: I:\adt-bundle-windows-x86_64\sdk\platform-tools\adb.exe devices`

运行runner4这步，一直停留这里了。。。。貌似没有找到我设备，
但是cmd输入：adb devices 列出我的设备。。

**Comment by Louis-me** [comment]
1.你的Devices.ini 中的设备名需要设置成你的手机设备名
2.电脑上尽量不要安装手机助手之类的，如果遇到adb 异常，请执行：
adb kill-server
adb start-server
